app = "ragslack-madli-updater"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

# This is a one-shot task, not a service
[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb" 