name: Daily Slack Database Update

on:
  schedule:
    # Run daily at 9:00 AM UTC (adjust timezone as needed)
    - cron: "0 9 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run incremental update
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_INDEX: ${{ secrets.PINECONE_INDEX }}
        run: |
          python slack_export/incremental_update.py

      - name: Upload logs (if needed)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: update-logs
          path: |
            last_update.json
            *.log
          retention-days: 7
